"""
 maintain all constant value in here
"""

constant_data = {
    "enviroment": "qa",
    "base_url": "http://127.0.0.1",
    "app_port_number": 8080,
    "log_file_name": "server.log",
    "app_secreat_key": "sdfsf65416534sdfsdf4653",
    "secure_type": "http",
    "search_dict": {
        "student": "student_data",
        "teacher": "teacher_data",
        "admin": "admin_data"
    },
    "search_dict_data": ["allcountrycode", "alldata"],
    "all_cities": ['Amsterdam',
'Rotterdam',
'The Hague (Den Haag)',
'Utrecht',
'Eindhoven',
'Tilburg',
'Groningen',
'Almere',
'Breda',
'Nijmegen',
'Enschede',
'Haarlem',
'Arnhem',
'Amersfoort',
'Zaanstad',
'Apeldoorn',
's-Hertogenbosch',
'Hoofddorp',
'Maastricht',
'Leiden',
'Dordrecht',
'Zoetermeer',
'Zwolle',
'Deventer',
'Delft',
'Alkmaar',
'Heerlen',
'Venlo',
'Leeuwarden',
'Amstelveen',
'Hilversum',
'Hengelo',
'Roosendaal',
'Purmerend',
'Oss',
'Schiedam',
'Spijkenisse',
'Vlaardingen',
'Almelo',
'Gouda',
'Zaandam',
'Lelystad',
'Alphen aan den Rijn',
'Hoorn',
'Velsen',
'Helmond',
'Leeuwarden',
'Leidschendam-Voorburg',
'Oosterhout,'
'Roermond'
]
}