"""
 maintain all constant value in here
"""

constant_data = {
    "enviroment": "qa",
    "base_url": "http://127.0.0.1",
    "app_port_number": 8080,
    "log_file_name": "server.log",
    "app_secreat_key": "sdfsf65416534sdfsdf4653",
    "secure_type": "http",
    "search_dict": {
        "student": "student_data",
        "teacher": "teacher_data",
        "admin": "admin_data"
    },
    "city_province_mapping": {
      "Aalsmeer": "North Holland",
      "Alkmaar": "North Holland",
      "Almelo": "Overijssel",
      "Almere": "Flevoland",
      "Amersfoort": "Utrecht",
      "Amsterdam": "North Holland",
      "Apeldoorn": "Gelderland",
      "Arnhem": "Gelderland",
      "Assen": "Drenthe",
      "Breda": "North Brabant",
      "Delft": "South Holland",
      "Den Bosch ('s-Hertogenbosch)": "North Brabant",
      "Den Haag (The Hague)": "South Holland",
      "Deventer": "Overijssel",
      "Dordrecht": "South Holland",
      "Ede": "Gelderland",
      "Eindhoven": "North Brabant",
      "Emmen": "Drenthe",
      "Enschede": "Overijssel",
      "Gouda": "South Holland",
      "Groningen": "Groningen",
      "Haarlem": "North Holland",
      "Haarlemmermeer": "North Holland",
      "Heerlen": "Limburg",
      "Helmond": "North Brabant",
      "Hengelo": "Overijssel",
      "Hilversum": "North Holland",
      "Hoofddorp": "North Holland",
      "Leeuwarden": "Friesland",
      "Leiden": "South Holland",
      "Lelystad": "Flevoland",
      "Maastricht": "Limburg",
      "Nijmegen": "Gelderland",
      "Oss": "North Brabant",
      "Roosendaal": "North Brabant",
      "Rotterdam": "South Holland",
      "Schiedam": "South Holland",
      "Sittard": "Limburg",
      "Tilburg": "North Brabant",
      "Utrecht": "Utrecht",
      "Venlo": "Limburg",
      "Vlaardingen": "South Holland",
      "Zaandam": "North Holland",
      "Zoetermeer": "South Holland",
      "Zwolle": "Overijssel"
    },
    "search_dict_data": ["allcountrycode", "alldata"],
}